### ISSUE TITLE
【依頼】ProtoSpace挙動確認	

### ISSUE THREAD

**Issue by mikity-i** [mikity-i/protospace-37292#1]
#本番環境URL
https://protospace-37292.herokuapp.com/

よろしくお願い致します。

**Comment by mo1015** [comment]
ご提出ありがとうございます！お待たせいたしました。
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [x] **ログイン状態のユーザーであっても、他のユーザーのプロトタイプ編集ページのURLを直接入力して遷移しようとすると、トップページにリダイレクトされるようにしましょう**
他のユーザーのプロトタイプ編集ページへ遷移できてしまいます。

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by mikity-i** [comment]
ご確認ありがとうございます。
ご指摘の箇所を修正致しました。
よろしくお願い致します。

**Comment by div-reviewer** [comment]
通知テストです

**Comment by snkw-works** [comment]
@mikity-i さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　**LGTM**です✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）

**Comment by mikity-i** [comment]
ありがとうございます！
